version: "3.9"

services:
  api_blue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_blue
    volumes:
      - ./backend:/app/backend
    networks:
      - zeronet

networks:
  zeronet:
    external: true